#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/vhhust/cloud-batch/config

server:
  port: 9999

#use native to include property files inside server-config instead of git
spring:
  profiles:
    active: native
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:#    console:#      enabled: true
#      settings:#        web-allow-others: true