external:
  property: Hello #from ${eureka.instance.instance_id}

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
  batch:
    initialize-schema: always #Avoids creation of job instance tables
    job:
      enabled: false #Avoids auto-execution of job when starting micro